runtime: nodejs20
service: admin

# 静的ファイルの設定
handlers:
  # 静的ファイル（JS、CSS、画像など）
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$
    expiration: 365d

  # すべてのリクエストをindex.htmlにリダイレクト（SPA用）
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

# 環境変数
env_variables:
  NODE_ENV: production

# リソース設定
resources:
  cpu: 0.5
  memory_gb: 0.25
  disk_size_gb: 1

# 自動スケーリング設定
automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.6
